### ISSUE TITLE
Email address does not work

### ISSUE THREAD

**Issue by mfoos** [sol-eng/connect-usage#4]
The email I just sent to sol-eng@rstudio.com bounced back. I will take my question to RStudio Community, but just FYI.

**Comment by slopp** [comment]
Thanks for the report, we'll update the docs to use the public alias; sales@rstudio.com

**Comment by slopp** [comment]
I didn't see a post on community, if you link the post here we'll be sure to take a look

**Comment by mfoos** [comment]
Got pulled into a meeting while scanning to make sure I wasn't duplicating - I'll make a post ASAP if appropriate, thanks!

**Comment by mfoos** [comment]
You know what, I think it's a version error 😳 thanks!
